Algoritmo "Conversão de Fº Para Cº "
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 09/09/2020
Var
 Fahrenheit, Centigrados: real


Inicio

  Escreva ("Qual a temperatura em graus Fahrenheit ")
  Leia (Fahrenheit)
  Centigrados<- (Fahrenheit- 32) * (5/9)
  Escreva (" A temperatura em graus centigrados será de: ", Centigrados)

Fimalgoritmo