Algoritmo "Par ou Ímpar ou Mult. de 3 "
Var
   N1:inteiro
Inicio
   Escreva("Digite um número: ")
   Leia(N1)
        Se (N1 % 2 = 0) entao
        Escreval("O número é par ")
        senao
        Escreval ("O número é impar ")
        Fimse
              Se (N1 % 3 = 0) entao
              Escreva ("Este número é um Múltiplo de 3 ")
              Senao
              Escreva ("Este número não é um Múltiplo de 3 ")
              Fimse
Fimalgoritmo